### ISSUE TITLE
Dokuwiki editor toolbar vanishes in Firefox and Chrome

### ISSUE THREAD

**Issue by SFITCS** [turnermm/epub#21]
Dokuwiki 2014-09-29d "Hrun" (Debian package), various installations with various plugins. epub 2015-02-15. 
Javascript console message _"Uncaught ReferenceError: Invalid left-hand side expression in postfix operation"_ (minify error?)

This is a recent event, likely the result of upgrading other plugins, however 1x1 didn't show _which_ one - only that removing or downgrading epub make the toolbar reappear.
The problem does not occur when using Konqueror web-browser.
Rolling back to the 2013-02-08 version of epub brings back the edit toolbar.

Example of other plugins used in an installation: abbr 2014-08-18, acl 2014-06-04, ajaxloader 2009-12-11, alphaindex 2008-10-18, authad 2014-04-03, authldap 2014-05-18, authmysql 2014-02-15, authpgsql 2014-02-15, authplain 2014-07-01, blockquote 2013-05-05, bookcreator 2015-06-11, bureaucracy 2015-01-22, cellbg 2013-10-09, columns 2015-05-30, config 2014-03-18, data 2015-05-16, dig 2015-02-26, do 2014-11-01, dw2pdf 2015-06-25, edittable 2015-06-17, epub 2013-02-08, extension 2014-06-15, fancysearch 2015-02-26, fckg 2014-12-15, fontsize2 2010-03-26, gallery 2014-05-18, hidden 2015-08-21, imagemap 2015-08-13, imgpaste 2015-02-26, info 2014-03-05, konsole 2015-08-18, log 2015-02-26, nslist 2015-02-26, odt 2015-02-26, pagebreak 2015-07-13, pagemod 2014-11-10, pagenav 2015-02-26, popularity 2013-10-14, qc 2015-06-17, revert 2013-11-21, safefnrecode 2012-07-28, searchpattern 2013-06-16c, sqlite 2015-05-04, todo 2014-11-26, toucher 2012-09-16, usercontact 2015-02-26, usermanager 2014-03-05, wikipediasnippet 2013-04-06, wrap 2015-07-19

**Comment by turnermm** [comment]
* You don't say which browser you are using when the error occurs.  I ran it in Iceweasel on Debian without a problem.  But my Iceweasel is old.
* Have you tried unloading all the other plugins except epub? 
* Disable compression and see if you can find where the error occurs.  The current error message is not specific enough, since it doesn't give the location of the error.  
* Between the current version and feb 2013 there have been about 50 commits, so knowing that it worked 2 1/2 years ago doesn't really help narrow things down.
* It's also possible that there is something in one of the pages that you are saving to your ebook that  is causing this.  So that would require a separate investigation.
